# Generated by Django 4.2.5 on 2023-10-10 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0023_agent_adhar_card_back_agent_adhar_card_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(choices=[('Add Leads', 'Add Leads'), ('Add Enquiry', 'Add Enquiry')], max_length=255),
        ),
        migrations.CreateModel(
            name='IndividualMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
